name: riverpod_sample
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  collection: ^1.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

